"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/browser";
import { Plus, Save, Trash2, UserRoundPlus, ShieldCheck, Link2 } from "lucide-react";

type Tenant={id:string;name:string;slug:string;tenant_status:string;subscription_plan:string;subscription_ends_at:string|null;max_products:number;max_users:number;directory_visible:boolean};
type Guide={id:string;title:string;description:string|null;content:string|null;youtube_url:string|null;external_url:string|null;sort_order:number;is_published:boolean};

export function CloudAdminManager({initialTenants,initialGuides,registrationEnabled}:{initialTenants:Tenant[];initialGuides:Guide[];registrationEnabled:boolean}){
 const supabase=createClient(); const [tenants,setTenants]=useState(initialTenants); const [guides,setGuides]=useState(initialGuides); const [registration,setRegistration]=useState(registrationEnabled); const [msg,setMsg]=useState("");
 const [tenant,setTenant]=useState({name:"",slug:"",plan:"starter",maxProducts:100,maxUsers:5,ends:""});
 const [guide,setGuide]=useState<Guide>({id:"",title:"",description:"",content:"",youtube_url:"",external_url:"",sort_order:0,is_published:true});
 async function createTenant(){setMsg("");const {data,error}=await supabase.rpc("cloud_create_tenant",{p_name:tenant.name,p_slug:tenant.slug,p_plan:tenant.plan,p_max_products:tenant.maxProducts,p_max_users:tenant.maxUsers,p_subscription_ends_at:tenant.ends?new Date(tenant.ends).toISOString():null});if(error){setMsg(error.message);return;}setMsg(`Tenant dibuat: ${data}`);location.reload();}
 async function assignOwner(id:string){const email=prompt("Email user yang sudah terdaftar di Supabase Auth:");if(!email)return;const {error}=await supabase.rpc("cloud_assign_owner",{p_tenant_id:id,p_email:email});setMsg(error?error.message:"Owner berhasil ditetapkan.");if(!error)location.reload();}
 async function inviteOwner(id:string){const email=prompt("Email Owner yang akan menerima link undangan:");if(!email)return;const {data,error}=await supabase.rpc("cloud_create_owner_invitation",{p_tenant_id:id,p_email:email});if(error){setMsg(error.message);return;}const link=`${window.location.origin}/cloud-invite?token=${encodeURIComponent(data.token)}`;try{await navigator.clipboard.writeText(link);setMsg(`Link Owner dibuat dan sudah disalin: ${link}`);}catch{setMsg(`Link Owner: ${link}`);}}
 async function saveTenant(t:Tenant){const {error}=await supabase.rpc("cloud_update_tenant",{p_tenant_id:t.id,p_status:t.tenant_status,p_plan:t.subscription_plan,p_max_products:Number(t.max_products),p_max_users:Number(t.max_users),p_subscription_ends_at:t.subscription_ends_at,p_directory_visible:t.directory_visible});setMsg(error?error.message:"Tenant diperbarui.");if(!error)location.reload();}
 async function saveGuide(){const {data,error}=await supabase.rpc("cloud_upsert_guide",{p_id:guide.id||null,p_title:guide.title,p_description:guide.description,p_content:guide.content,p_youtube_url:guide.youtube_url,p_external_url:guide.external_url,p_sort_order:Number(guide.sort_order),p_is_published:guide.is_published});setMsg(error?error.message:`Panduan tersimpan: ${data}`);if(!error){setGuide({id:"",title:"",description:"",content:"",youtube_url:"",external_url:"",sort_order:0,is_published:true});location.reload();}}
 async function deleteGuide(id:string){if(!confirm("Hapus panduan ini?"))return;const {error}=await supabase.rpc("cloud_delete_guide",{p_id:id});setMsg(error?error.message:"Panduan dihapus.");if(!error)location.reload();}
 return <div className="cloudAdminManager">
 <section className="adminPanel"><h2><ShieldCheck size={18}/> Pengaturan Cloud</h2><div className="adminSettingRow"><div><strong>Pendaftaran Tenant Mandiri</strong><small>{registration ? "Aktif — calon pelanggan dapat membuat akun dan tenant sendiri." : "Nonaktif — tenant hanya dibuat melalui Super Admin dan akses diberikan lewat link undangan."}</small></div><label className="switch"><input type="checkbox" checked={registration} onChange={async e=>{const next=e.target.checked;setRegistration(next);const {error}=await supabase.rpc("set_cloud_registration_enabled",{p_enabled:next});if(error){setRegistration(!next);setMsg(error.message)}else setMsg(next?"Pendaftaran tenant mandiri diaktifkan.":"Pendaftaran tenant mandiri dinonaktifkan.")}}/><span></span></label></div></section><section className="adminPanel"><h2>Create Tenant</h2><div className="adminFormGrid"><label>Nama Tenant<input value={tenant.name} onChange={e=>setTenant({...tenant,name:e.target.value})}/></label><label>Slug<input value={tenant.slug} onChange={e=>setTenant({...tenant,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})}/></label><label>Plan<input value={tenant.plan} onChange={e=>setTenant({...tenant,plan:e.target.value})}/></label><label>Max Produk<input type="number" value={tenant.maxProducts} onChange={e=>setTenant({...tenant,maxProducts:Number(e.target.value)})}/></label><label>Max User<input type="number" value={tenant.maxUsers} onChange={e=>setTenant({...tenant,maxUsers:Number(e.target.value)})}/></label><label>Berakhir<input type="date" value={tenant.ends} onChange={e=>setTenant({...tenant,ends:e.target.value})}/></label></div><button className="primaryButton" onClick={()=>void createTenant()}><Plus size={17}/> Create Tenant</button></section>
 <section className="adminPanel"><h2>Tenant Management</h2><div className="adminTable">{tenants.map(t=><div className="adminRow" key={t.id}><div><strong>{t.name}</strong><small>/{t.slug}</small></div><select value={t.tenant_status} onChange={e=>setTenants(tenants.map(x=>x.id===t.id?{...x,tenant_status:e.target.value}:x))}><option>active</option><option>expiring</option><option>expired</option><option>suspended</option></select><input value={t.subscription_plan} onChange={e=>setTenants(tenants.map(x=>x.id===t.id?{...x,subscription_plan:e.target.value}:x))}/><input type="number" value={t.max_products} onChange={e=>setTenants(tenants.map(x=>x.id===t.id?{...x,max_products:Number(e.target.value)}:x))}/><input type="number" value={t.max_users} onChange={e=>setTenants(tenants.map(x=>x.id===t.id?{...x,max_users:Number(e.target.value)}:x))}/><div className="adminActions"><button onClick={()=>void saveTenant(t)} title="Simpan"><Save size={16}/></button><button onClick={()=>void assignOwner(t.id)} title="Assign Owner yang sudah punya akun"><UserRoundPlus size={16}/></button><button onClick={()=>void inviteOwner(t.id)} title="Buat link undangan Owner"><Link2 size={16}/></button></div></div>)}</div></section>
 <section className="adminPanel"><h2>Panduan</h2><div className="adminFormGrid"><label>Judul<input value={guide.title} onChange={e=>setGuide({...guide,title:e.target.value})}/></label><label>Urutan<input type="number" value={guide.sort_order} onChange={e=>setGuide({...guide,sort_order:Number(e.target.value)})}/></label><label>URL YouTube<input value={guide.youtube_url??""} onChange={e=>setGuide({...guide,youtube_url:e.target.value})} placeholder="https://www.youtube.com/watch?v=..."/></label><label>URL Referensi / Alamat Web<input value={guide.external_url??""} onChange={e=>setGuide({...guide,external_url:e.target.value})} placeholder="https://..."/></label><label className="full">Deskripsi<input value={guide.description??""} onChange={e=>setGuide({...guide,description:e.target.value})}/></label><label className="full">Isi Panduan<textarea rows={7} value={guide.content??""} onChange={e=>setGuide({...guide,content:e.target.value})}/></label></div><label className="checkRow"><input type="checkbox" checked={guide.is_published} onChange={e=>setGuide({...guide,is_published:e.target.checked})}/> Publikasikan</label><button className="primaryButton" onClick={()=>void saveGuide()}><Save size={17}/> Simpan Panduan</button><div className="adminGuideList">{guides.map(g=><article key={g.id}><div><strong>{g.title}</strong><small>{g.is_published?"Published":"Draft"} · {g.youtube_url||"Tanpa YouTube"} · {g.external_url||"Tanpa URL eksternal"}</small></div><button onClick={()=>void deleteGuide(g.id)}><Trash2 size={16}/></button></article>)}</div></section>{msg?<div className="formMessage">{msg}</div>:null}</div>;
}
